import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/sidebar/sidebar";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { Toaster } from "@/components/ui/toaster"
const montserrat = Montserrat({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "RABEL CAFE | GRKNDEV QR MENUS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en h-full w-full">
      <body
        className={cn(montserrat.className, "flex flex-col sm:flex-row h-full")}
      >
        <Toaster />
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          forcedTheme="light"
          disableTransitionOnChange
        >
          <SideBar />

          <main className="w-full">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
