import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/sidebar/sidebar";
import { cn } from "@/lib/utils";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en h-full ">
      <body className={cn(montserrat.className, "flex flex-row h-full")}>
        <SideBar />

        <main>{children}</main>
      </body>
    </html>
  );
}
